/* tslint:disable */
/* eslint-disable */
/**
 * Cars example
 * The cars API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Car
 */
export interface Car {
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof Car
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    modelName: string;
}

/**
 * Check if a given object implements the Car interface.
 */
export function instanceOfCar(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "modelName" in value;

    return isInstance;
}

export function CarFromJSON(json: any): Car {
    return CarFromJSONTyped(json, false);
}

export function CarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Car {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'price': json['price'],
        'modelName': json['modelName'],
    };
}

export function CarToJSON(value?: Car | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'price': value.price,
        'modelName': value.modelName,
    };
}

