/* tslint:disable */
/* eslint-disable */
/**
 * Cars example
 * The cars API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Car,
} from '../models';
import {
    CarFromJSON,
    CarToJSON,
} from '../models';

export interface CarsControllerCreateRequest {
    body: object;
    xMyHeader?: string;
}

export interface CarsControllerFindByQueryRequest {
    modelName: string;
    xMyHeader?: string;
}

export interface CarsControllerFindOneRequest {
    id: string;
    xMyHeader?: string;
}

export interface CarsControllerFindPagenatedByQueryRequest {
    modelName: string;
    xMyHeader?: string;
}

export interface CarsControllerRemoveRequest {
    id: string;
    xMyHeader?: string;
}

export interface CarsControllerUpdateRequest {
    id: string;
    body: object;
    xMyHeader?: string;
}

/**
 * 
 */
export class CarsApi extends runtime.BaseAPI {

    /**
     */
    async carsControllerCreateRaw(requestParameters: CarsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling carsControllerCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xMyHeader !== undefined && requestParameters.xMyHeader !== null) {
            headerParameters['X-MyHeader'] = String(requestParameters.xMyHeader);
        }

        const response = await this.request({
            path: `/cars`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async carsControllerCreate(requestParameters: CarsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.carsControllerCreateRaw(requestParameters, initOverrides);
    }

    /**
     */
    async carsControllerFindByQueryRaw(requestParameters: CarsControllerFindByQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.modelName === null || requestParameters.modelName === undefined) {
            throw new runtime.RequiredError('modelName','Required parameter requestParameters.modelName was null or undefined when calling carsControllerFindByQuery.');
        }

        const queryParameters: any = {};

        if (requestParameters.modelName !== undefined) {
            queryParameters['modelName'] = requestParameters.modelName;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xMyHeader !== undefined && requestParameters.xMyHeader !== null) {
            headerParameters['X-MyHeader'] = String(requestParameters.xMyHeader);
        }

        const response = await this.request({
            path: `/cars`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async carsControllerFindByQuery(requestParameters: CarsControllerFindByQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.carsControllerFindByQueryRaw(requestParameters, initOverrides);
    }

    /**
     */
    async carsControllerFindOneRaw(requestParameters: CarsControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Car>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling carsControllerFindOne.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xMyHeader !== undefined && requestParameters.xMyHeader !== null) {
            headerParameters['X-MyHeader'] = String(requestParameters.xMyHeader);
        }

        const response = await this.request({
            path: `/cars/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CarFromJSON(jsonValue));
    }

    /**
     */
    async carsControllerFindOne(requestParameters: CarsControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Car> {
        const response = await this.carsControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async carsControllerFindPagenatedByQueryRaw(requestParameters: CarsControllerFindPagenatedByQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.modelName === null || requestParameters.modelName === undefined) {
            throw new runtime.RequiredError('modelName','Required parameter requestParameters.modelName was null or undefined when calling carsControllerFindPagenatedByQuery.');
        }

        const queryParameters: any = {};

        if (requestParameters.modelName !== undefined) {
            queryParameters['modelName'] = requestParameters.modelName;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xMyHeader !== undefined && requestParameters.xMyHeader !== null) {
            headerParameters['X-MyHeader'] = String(requestParameters.xMyHeader);
        }

        const response = await this.request({
            path: `/cars/pagenated`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async carsControllerFindPagenatedByQuery(requestParameters: CarsControllerFindPagenatedByQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.carsControllerFindPagenatedByQueryRaw(requestParameters, initOverrides);
    }

    /**
     */
    async carsControllerRemoveRaw(requestParameters: CarsControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling carsControllerRemove.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xMyHeader !== undefined && requestParameters.xMyHeader !== null) {
            headerParameters['X-MyHeader'] = String(requestParameters.xMyHeader);
        }

        const response = await this.request({
            path: `/cars/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async carsControllerRemove(requestParameters: CarsControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.carsControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     */
    async carsControllerUpdateRaw(requestParameters: CarsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling carsControllerUpdate.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling carsControllerUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xMyHeader !== undefined && requestParameters.xMyHeader !== null) {
            headerParameters['X-MyHeader'] = String(requestParameters.xMyHeader);
        }

        const response = await this.request({
            path: `/cars/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async carsControllerUpdate(requestParameters: CarsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.carsControllerUpdateRaw(requestParameters, initOverrides);
    }

}
